spring:
  datasource:
#    url: jdbc:mysql://47.110.156.18:3306/sczn_eshop_test1?useUnicode=true&useJDBCCompliantTimezoneShift=true&serverTimezone=UTC
#    username: sczn
#    password: sczn159357
    url: jdbc:mysql://localhost:3306/ice_cms?useUnicode=true&useJDBCCompliantTimezoneShift=true&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
mybatis-plus:
  #  mybatis-plus??sql??
  # configuration:
  # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/ttice/mapper/xml/*.xml
server:
  port: 8181
myhost: https://frp.semsx.com

  #  ??ssh https
#  ssl:
#    key-store: classpath:Myssh.pfx
#    key-store-password: ko674hz8x35
#    key-store-type: PKCS12
